
#
# Create the private zone first
#

- name: Create DNS zone for openshift
  route53_zone:
     zone: "{{namespace}}.local"
     state: "present"
     vpc_id: "{{vpc_id}}"
     vpc_region: "{{region}}"
     comment: "Internal zone for {{namespace}}"
  register: aws_zone

#
# Masters
#

- name: Add private master A record (e.g. master.ocp.local)
  route53:
    zone: "{{namespace}}.local"
    record: "master.{{namespace}}.local"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='private_ip')|join(',') }}"
#    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes

- name: Add public master A record (e.g. master.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "master.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='public_ip')|join(',') }}"
#    wait: yes
    command: "create"
    overwrite: yes

- name: Add private master A records (e.g. master1.ocp.local)
  route53:
    zone: "{{namespace}}.local"
    record: "master{{item.index}}.{{namespace}}.local"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
#    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ all_master_nodes }}"

- name: Add public master A records (e.g. master1.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "master{{item.index}}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{item.public_ip}}"
#    wait: yes
    command: "create"
    overwrite: yes
  with_items: "{{ all_master_nodes }}"

#
# Application nodes
#

- name: Add private app node A records (e.g. app1.ocp.local)
  route53:
    zone: "{{namespace}}.local"
    record: "app{{item.index}}.{{namespace}}.local"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
#    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ all_app_nodes }}"

#
# Other
#

- name: Add public wildcard dns
  route53:
    zone: "{{public_dns_zone}}"
    record: "*.{{public_subdomain_prefix}}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='public_ip')|join(',') }}"
#    wait: yes
    command: "create"
    overwrite: yes