
- name: Create DNS zone for openshift
  route53_zone:
     zone: "{{namespace}}.local"
     state: "present"
     vpc_id: "{{vpc_id}}"
     vpc_region: "{{region}}"
     comment: "Internal zone for {{namespace}}"
  register: aws_zone

- name: Add master A record 
  route53:
    zone: "{{namespace}}.local"
    record: "master.{{namespace}}.local"
    type: A
    ttl: 300
    value: "{{ all_masters|map(attribute='private_ip')|join(',') }}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes

- name: Add node A records 
  route53:
    zone: "{{namespace}}.local"
    record: "node{{item.index}}.{{namespace}}.local"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ all_nodes }}"

- name: Add public master A record
  route53:
    zone: "{{public_dns_zone}}"
    record: "{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_masters|map(attribute='public_ip')|join(',') }}"
    wait: yes
    command: "create"
    overwrite: yes

- name: Add public wildcard dns
  route53:
    zone: "{{public_dns_zone}}"
    record: "*.{{public_subdomain_prefix}}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_masters|map(attribute='public_ip')|join(',') }}"
    wait: yes
    command: "create"
    overwrite: yes