
- name: List all hosted zones
  route53_facts:
    query: hosted_zone
  register: hosted_zones

- name: Delete master and bastion routes
  include: delete-route.yml zone="{{ namespace }}.local" record="master{{item}}.{{ namespace }}.local" private_zone="true"
  with_sequence: start=1 end={{master_nodes|int}}
  wait: yes
  ignore_errors: true
  
- name: Delete node routes
  include: delete-route.yml zone="{{ namespace }}.local" record="node{{item}}.{{ namespace }}.local" private_zone="true"
  with_sequence: start=1 end={{app_nodes|int}}
  wait: yes
  ignore_errors: true
  
- name: Delete private DNS zone
  route53_zone:
    zone: "{{namespace}}.local"
    state: "absent"
    vpc_region: "{{region}}"
  wait: yes
