
- name: Prepare AMI and Infrastructure 
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vpc
    - role: create_default_security_groups
  
- name: Build AMI
  hosts: localhost
  roles:
    - role: build_base_ami

- name: Teardown AMI and Infrastructure
  hosts: localhost
  roles:
  - role: teardown_default_security_groups
  - role: teardown_vpc