
- name: Prepare Infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vpc
    - role: create_security_groups
    - role: create_virtual_machines
    - role: create_dns
    - role: create_ssh
    - role: create_host_groups

- name: Prepare nodes
  hosts: created_nodes
  vars:
    state: 'present'
  roles:
    - update_virtual_machines
    - prepare_nodes
  remote_user: "{{ deploy_user }}"

- name: Install OpenShift
  hosts: localhost
  roles:
    - role: prepare_bastion
    - role: install_openshift
  remote_user: "{{ deploy_user }}"