
- name: Prepare Infrastructure
  hosts: localhost

  gather_facts: false

  roles:
    - role: create_vpc
#    - role: create_default_security_group
    - role: create_security_groups
    - role: create_virtual_machines
    - role: create_dns
    - role: create_ssh
    - role: create_host_groups


#- name: Update virtual machines
#  hosts: created_vms
#  remote_user: "{{ deploy_user }}"

#  vars:
#    state: 'present'

#  roles:
#    - update_virtual_machines


- name: Setup nodes
  hosts: created_nodes
  remote_user: "{{ deploy_user }}"

  vars:
    state: 'present'

  roles:
    - role: openshift_prepare


- name: Install OpenShift
  hosts: localhost
  remote_user: "{{ deploy_user }}"

  roles:
    - role: openshift_install