- name: Prepare Infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vpc
#    - role: create_default_security_group
    - role: create_security_groups
    - role: create_virtual_machines
    - role: create_dns
    