
- name: Prepare infrastructure and bastion host
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vpc
    - role: create_default_security_groups
    - role: provision_bastion

- name: Update instance
  hosts: created_instances
  vars:
    state: 'present'
  roles:
    - configure_docker
  remote_user: "{{ instance_user }}"