
- name: Prepare infrastructure and bastion host
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vpc
    - role: create_default_security_groups
    - role: create_bastion
    - role: prepare_bastion
