
- name: Prepare infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vpc
    - role: create_security_groups
    - role: create_instances
    - role: create_dns
    - role: create_ssh
    - role: create_host_groups

- name: Update instance
  hosts: created_instances
  vars:
    state: 'present'
  roles:
    - configure_docker
  remote_user: "{{ instance_user }}"

- name: Prepare inventories
  hosts: localhost
  roles:
    - role: prepare_inventories