
- name: Install essential packages on nodes
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "ntp"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "docker"
#      - "docker-1.12.6"
      - "NetworkManager"
    state: "present"
  become: true

# see https://github.com/openshift/openshift-ansible/issues/5236 and
# https://github.com/openshift/openshift-ansible/issues/4950 
- name: Enable NetworkManager
  shell: "systemctl enable NetworkManager && systemctl restart NetworkManager"
  become: true

- name: Update Docker config
  shell: echo "INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'" >> /etc/sysconfig/docker
  become: true
  
- name: Prepare Docker storage configuration
  template:
    src: "../files/docker-storage-setup"
    dest: "/etc/sysconfig/docker-storage-setup"
  become: true

- name: Stop Docker
  shell: "systemctl stop docker"
  become: true

- name: Configure Docker storage
  command: "docker-storage-setup"
  become: true
  ignore_errors: true

- name: Enable and restart Docker
  shell: "systemctl enable docker && systemctl restart docker"
  become: true