
- name: Upgrade packages on all nodes
  yum: name=* state=latest
  become: true

- name: Install EPEL
  yum:
    name:
      - "epel-release"
    state: "present"
  become: true

- name: Install essential packages
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "ntp"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "docker"
#      - "docker-1.12.6"
      - "NetworkManager"
    state: "present"
  become: true

#
# see 
# https://github.com/openshift/openshift-ansible/issues/5236 
# and
# https://github.com/openshift/openshift-ansible/issues/4950 
#
- name: Enable NetworkManager
  shell: "systemctl enable NetworkManager && systemctl restart NetworkManager"
  become: true