
- name: Find AMI
  ec2_ami_find:
    owner: self
    ami_tags:
      Name: "{{ ami_name }}"
    region: "{{region}}"
  register: "ami_find"

- include_tasks: create-masters.yml

- include_tasks: create-app-nodes.yml

- include_tasks: create-infra-nodes.yml
  when: infra_nodes > 0

- name: Wait for masters SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_master_nodes }}"

- name: Wait for app node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_app_nodes }}"

- name: Wait for infra node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_infra_nodes }}"
  when: infra_nodes > 0