
- name: Find AMI
  ec2_ami_find:
    owner: self
    ami_tags:
      Name: "{{ ami_name }}"
    region: "{{region}}"
  register: "ami_find"
  
- name: Provision bastion host
  include: provision-bastion.yml

- name: Install additional packages on bastion
  yum:
    name:
      - "git"
      - "@Development Tools"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      - "ansible"
    state: "present"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ instance_user }}"
  become: true

- name: Checkout openshift-ansible playbooks
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{ instance_user }}/openshift-ansible"
    version: "{{ openshift_branch }}"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ instance_user }}"