
- name: Find AMI
  ec2_ami_find:
    owner: self
    ami_tags:
      Name: "{{ ami_name }}"
    region: "{{region}}"
  register: "ami_find"
  
- name: Provision bastion host
  include: provision-bastion.yml

- name: Install additional packages on bastion
  yum:
    name:
      - "git"
      - "@Development Tools"
      - "java-1.8.0-openjdk"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      # needed for latest ansible
      - "python-crypto"
      - "python-keyczar"
      - "python-httplib2"
      - "python-paramiko"
      - "python2-jmespath"
      - "sshpass"
    state: "present"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ instance_user }}"
  become: true

- name: Install Ansible from .rpm
  shell: >
    cd /tmp

    curl -L -o {{ansible_rpm}} {{ansible_rpm_url}}

    rpm -Uvh {{ansible_rpm}}
    
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ instance_user }}"  
  become: true

- name: Checkout openshift-ansible playbooks
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{ instance_user }}/openshift-ansible"
    version: "{{ openshift_branch }}"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ instance_user }}"

