
- name: Upgrade packages on bastion
  yum: name=* state=latest
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ deploy_user }}"
  become: true

- name: Install EPEL
  yum:
    name:
      - "epel-release"
    state: "present"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ deploy_user }}"
  become: true

- name: Install additional packages on bastion
  yum:
    name:
      - "git"
      - "@Development Tools"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      - "ansible"
    state: "present"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ deploy_user }}"
  become: true

- name: Checkout openshift-ansible playbooks
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{ deploy_user }}/openshift-ansible"
    version: "{{ openshift_branch }}"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ deploy_user }}"

- name: Copy script for OpenShift istallation
  template:
    src: "../files/install-openshift.sh"
    dest: "~{{ deploy_user }}/install-openshift.sh"
    mode: "0775"
  delegate_to: "{{ bastion_public_ip }}"
  remote_user: "{{ deploy_user }}"