
- name: Copy single master inventory
  template:
    src: "../files/single_master_inventory.cfg"
    dest: "~{{ instance_user }}/single_master_inventory.cfg"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"

- name: Copy multi-master inventory
  template:
    src: "../files/multi_master_inventory.cfg"
    dest: "~{{ instance_user }}/multi_master_inventory.cfg"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"
  when: master_nodes > 1
