
- name: Provision bastion
  ec2:
    instance_type: "{{bastion_ami_size}}"
    image:  "{{ami_id}}"
    region: "{{region}}"
    spot_price: "{{ bastion_spot_price }}"
    spot_wait_timeout: 300
    wait: true
    key_name: "{{key_name}}"
    vpc_subnet_id: "{{subnet_facts['subnet']['id']}}"
    group: ['{{namespace}}_vpc', '{{namespace}}_bastion']
    count_tag:
      Name: "bastion_{{namespace}}"
    instance_tags:
      Name: "bastion_{{namespace}}"
      namespace: "{{namespace}}"
    exact_count: 1
    assign_public_ip: yes
  register: ec2_bastion

- name: Register VM facts
  set_fact:
   bastion_private_ip: "{{ec2_bastion['tagged_instances'][0]['private_ip']}}"
   bastion_public_ip: "{{ec2_bastion['tagged_instances'][0]['public_ip']}}"
  
- name: Wait for SSH to come up
  wait_for:
    host: '{{ item }}'
    port: 22
    delay: 60
    timeout: 300
    state: started
  with_items:
    - "{{ bastion_public_ip }}"