
- name: Add master nodes to created_nodes group
  add_host:
    name={{ item.public_ip }}
    groups=created_nodes
    instance_name={{ item.cn }}
  with_items: "{{ all_master_nodes }}"

- name: Add app nodes to created_nodes group
  add_host:
    name={{ item.public_ip }}
    groups=created_nodes
    instance_name={{ item.cn }}
  with_items: "{{ all_app_nodes }}"

- debug:
  msg:
    - "{{ created_nodes }}"