
- name: Create a new instance
  include: provision-instance.yml

- name: Update the instance
  include: update-instance.yml

- name: Register a new AMI
  ec2_ami:
    instance_id: "{{ instance_id }}"
    region: "{{ region }}"
    name: "{{ ami_name }}"
    tags:
      Name: "{{ ami_name }}"
    wait: yes
  register: base_image

- name: Destroy the active instance
  include: destroy-instance.yml
