
- name: Find AMI
  ec2_ami_find:
     ami_id: "{{ami_id}}"
     region: "{{region}}"
  register: "ami_find"

- name: Provision masters
  include: create-masters.yml

- name: Provision app nodes
  include: create-nodes.yml

  
- name: Wait for masters SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_masters }}"

- name: Wait for node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_nodes }}"