
- name: Find AMI
  ec2_ami_find:
     ami_id: "{{ami_id}}"
     region: "{{region}}"
  register: "ami_find"

- name: Provision masters
  include: create-masters.yml

- name: Provision app nodes
  include: create-app-nodes.yml

- name: Provision infra nodes
  include: create-infra-nodes.yml
  when: infra_nodes > 0

- name: Wait for masters SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_master_nodes }}"

- name: Wait for app node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_app_nodes }}"

- name: Wait for infra node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_infra_nodes }}"