
- name: Prepare infrastructure and bastion host
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../roles/create_vpc
    - role: ../roles/create_default_security_groups
    - role: ../roles/provision_bastion

- name: Update instance
  hosts: created_instances
  vars:
    state: 'present'
  roles:
    - ../roles/configure_docker
  remote_user: "{{ instance_user }}"