
- name: Prepare infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../roles/create_vpc
    - role: ../roles/create_security_groups

- name: Prepare single node
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../roles/provision_single_node

- name: Update instances
  hosts: created_instances
  vars:
    state: 'present'
  roles:
    - ../roles/configure_docker
  remote_user: "{{ instance_user }}"

- name: Install OpenShift
  hosts: created_instances
  vars:
    openshift_version: v3.7.1
    openshift_cli_url: "https://github.com/openshift/origin/releases/download/v3.7.1/openshift-origin-client-tools-v3.7.1-ab0f056-linux-64bit.tar.gz"
    openshift_logging: false
    openshift_metrics: false
    ocp_root: "/opt/openshift"
  roles:
    - role: ../roles/install_cluster_up
  remote_user: "{{ instance_user }}"

